1. Fix distance metric to take into account periodic boundary conditions
1. Need to incorporate particle lifetimes (exponential decay)
2. Need to incorporate rate of new particles being formed
2. We only care about the minimum distance for an individual particle
3. New particle can not form at a site with an existing particle
3. N will change constantly
4. In the physical process when two particles are close enoug to activate they "dissapear"

In [55]:
import collections
import random
import numpy as np
from scipy.spatial import distance

X = 99
Y = 99
Z = 99
N = 10

In [92]:
def init():
    x = np.random.randint(X, size=(N,1))
    y = np.random.randint(Y, size=(N,1))
    z = np.random.randint(Z, size=(N,1))
    p = np.concatenate((x,y,z), axis=1)
    return p

In [60]:
def min_distance(p):
    d = distance.cdist(p, p, 'euclidean')
    np.fill_diagonal(d,np.inf)
    m_d = np.amin(d,axis=1)
    return m_d

In [112]:
def update(p):
    mx = np.full((N,1), X+1, dtype=np.int8)
    my = np.full((N,1), Y+1, dtype=np.int8)
    mz = np.full((N,1), Z+1, dtype=np.int8)
    m = np.concatenate((mx,my,mz), axis=1)
    step = np.random.choice((-1,0,1),(N,3))
    r = (p + step) % m
    return r

In [107]:
p = init()
data = []
for i in range(99):
    data.extend(list(min_distance(p)))
    p = update(p)

In [96]:
data

[36.124783736376884,
 46.733285782191693,
 24.06241883103193,
 12.041594578792296,
 24.207436873820409,
 44.294469180700204,
 24.06241883103193,
 12.041594578792296,
 21.470910553583888,
 21.470910553583888,
 33.719430600174732,
 45.880278987817846,
 25.514701644346147,
 14.177446878757825,
 24.207436873820409,
 42.118879377305376,
 24.207436873820409,
 14.177446878757825,
 22.649503305812249,
 22.649503305812249,
 36.069377593742864,
 43.68065933568311,
 22.869193252058544,
 14.456832294800961,
 23.280893453645632,
 42.118879377305376,
 22.869193252058544,
 14.456832294800961,
 21.283796653792763,
 21.283796653792763,
 33.301651610693426,
 43.54308211415448,
 23.173260452512935,
 44.181444068749045,
 23.173260452512935,
 44.204072210600685,
 23.2163735324878,
 44.204072210600685,
 21.470910553583888,
 21.470910553583888,
 33.719430600174732,
 42.379240200834182,
 21.840329667841555,
 16.031219541881399,
 21.679483388678801,
 46.540305112880382,
 21.679483388678801,
 16.031219541881399

In [111]:
update(init())

[[ 1  0  1]
 [ 1  0  0]
 [ 0 -1 -1]
 [ 0 -1  1]
 [ 1 -1  0]
 [-1  0 -1]
 [ 1 -1 -1]
 [-1 -1  0]
 [ 1  1  1]
 [ 0  0  1]]


array([[81, 76, 95],
       [48, 51, 34],
       [32, 91, 20],
       [ 0, 37, 48],
       [59, 18, 53],
       [24, 66, 97],
       [82, 10, 92],
       [53,  0, 45],
       [33, 56, 26],
       [74, 73, 78]])